from pydantic import BaseModel, Field
from typing import Optional, Dict

class AnalyzeResponse(BaseModel):
    """
    Response DTO for document analysis.
    """
    feedback: str = Field(..., description="Overall feedback generated by the LLM.")
    scores: Dict[str, float] = Field(..., description="Scores for different dimensions (e.g., {'clarity': 85.5, 'correctness': 92.0}).")
    overall_score: Optional[float] = Field(None, description="Optional overall score calculated from dimension scores.")
    parsed_content: Optional[str] = Field(None, description="Optional parsed content of the document.")